language: objective-c
osx_image: xcode8

cache:
  - cocoapods

env:
  global:

  - WORKSPACE=IDCardScanner.xcworkspace
  - PROJECT=IDCardScanner.xcodeproj
  - SCHEME=IDCardScanner
  - SDK=iphonesimulator


script:
  # - pod install
  - xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -sdk "$SDK" -configuration GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | xcpretty -c 
