language: objective-c
osx_image: xcode8

cache:
  - cocoapods

env:
  global:

  - WORKSPACE=IDCardScanner.xcworkspace
  - PROJECT=IDCardScanner.xcodeproj
  - SCHEME=IDCardScanner
  - SDK=iphonesimulator


script: 
  - xcodebuild build -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -configuration GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES ONLY_ACTIVE_ARCH=YES | xcpretty -c 
after_success:
  - bash <(curl -s https://codecov.io/bash)