language: objective-c

cache:
  - cocoapods

script: 
  - xctool -workspace IDCardScanner.xcworkspace -scheme IDCardScanner build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)